headers:
  robots: 'noindex,nofollow' # Do not crawl
  x-robots-tag: 'noindex,nofollow' # Do not crawl
  cache-control: 'no-cache, no-store, must-revalidate' # Http 1.1
  pragma: 'no-cache' # Http 1.0
  expires: 0 # Proxies

logger:
  driver: simple
  debugging: true

storage: simple

connection: null
